### ISSUE TITLE
rerouting - root to map page...as guest user

### ISSUE THREAD

**Issue by kevinzhangftw** [digitalSalt/GeoBox#96]
Re route to maps as guest user
guest detection - if guest, change header bar (login instead of logout), + will link to signup(possibly disabled?)

**Comment by digitalSalt** [comment]
we should discuss whether admins, upon login, should be routed to the map rather than the admin home page. 
for: 
* since coordinates are only submitted to the server(atomic with file fetching) when the map is loaded, if the admin tries to upload document without having first visited the map page, upload will fail with ('latitude can't be blank')

against: 
* we are the only admin users for this app (we as in dev team). In that sense, this doesn't really matter.

**Comment by digitalSalt** [comment]
done on dev as of 318351dd8b197e3d0dc9a52d7c5c56f7730ece7a
